### ISSUE TITLE
Preprocessing: file not found error on Windows

### ISSUE THREAD

**Issue by Lumik7** [univie-datamining-team3/assignment2#15]
Running ```make_dataset.py --download False --preprocessing True``` introduces a file not found error on Windows due to this code snippet in ```Preprocessing.preprocess()``` :
```
if filename is not None:
                with open("../../data/" + filename, "wb") as file:
                    file.write(pickle.dumps(preprocessed_data))
```
because the "/" is not supported.

**Comment by Lumik7** [comment]
I will fix this bug by using ```os.path.join``` syntax and using ```setup_directory``` to make sure the directory exists.

**Comment by Lumik7** [comment]
The bug has been fixed. The saving process is now OS independent. 
Close issue

**Comment by rmitsch** [comment]
Sorry, didn't think of that. Thanks for the fix.

**Comment by Lumik7** [comment]
no problem, forgot to fix the same bug in restore_preprocessed_data_from_disk. This is fixed now as well
