### ISSUE TITLE
Preprocessing: Improve speed of paa calculation

### ISSUE THREAD

**Issue by Lumik7** [univie-datamining-team3/assignment2#16]
The paa is running quite long, right now its about 20 minutes. Try to improve the runtime and memory efficiency by enhancing the code.

**Comment by Lumik7** [comment]
@MoBran  I removed some of the deepcopies to speed up the code, runtime is now 8 minutes instead of 20. maybe you could take a look and run it through your testing scripts, to see if everything runs as expected

**Comment by rmitsch** [comment]
Updates look reasonable to me.

**Comment by Lumik7** [comment]
@MoBran if you agree I would merge the branch and close this issue
