### ISSUE TITLE
Preprocessing: Cut trips in 30 second time snippets

### ISSUE THREAD

**Issue by Lumik7** [univie-datamining-team3/assignment2#17]
Implement a method in  ```preprocessing.py``` to handle the following points:
- cutting the trips to 30 second snippets per row and 30*20(hertz rate)=600 columns
- Save the new table as csv file in ```data/preprocessed```
- Add this new method to the ```preprocess()``` method
- each entry of the table is the "total" value 

Update:
- implement distance calculation

**Comment by Lumik7** [comment]
@rmitsch  @MoBran 
The cutting of the trip segments works now and has been added in this [commit](https://github.com/univie-datamining-team3/assignment2/commit/123099e647b03755a46ed2b3fe7441ea1ca9ba3a) and [this one](https://github.com/univie-datamining-team3/assignment2/commit/a60fb31e0d6815e4f572dbd8730d182a62545f57).  Still to do are the distance calculation mentioned for the clustering in Subtask 5 of the assignment. I could now merge my progress with the master branch or implement the distance calculation as well and merge afterwards. 
I did some basic visualisation with TSNE in this [notebook](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/3.0-lm-visualisation-trip-segments.ipynb) where you can see that there is no real structure in the plot when only using the "total" column values. So it would make sense that I also implement the distance calculation.

**Comment by rmitsch** [comment]
I'd merge after the distance calculation is completed. Regarding t-SNE: Did you try visualizing it with > 2 dimensions? The intrinsic dimensionality might be higher; maybe there are more discernible structures in a higher-dim. space.

**Comment by Lumik7** [comment]
Ok, then I will implement the distance function as well, but I had some issues with it, see issue #18.

I only tried it with 2 dimensions. I won't be able to do anything today, but if you're interested feel free to checkout my [branch](https://github.com/univie-datamining-team3/assignment2/tree/lukas). In order to produce the dataset you need to call
 ```make_dataset.py --download False --preprocessing True```

**Comment by Lumik7** [comment]
I implemented the distance calculation with the [scipy.spatial.distance.cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html) which is really fast, less than a minute for all trips, in this [commit](https://github.com/univie-datamining-team3/assignment2/commit/5881e14e54596edc5e81506f44e8a10efab79b47). You can see the new visualisations [here](https://github.com/univie-datamining-team3/assignment2/blob/lukas/notebooks/3.0-lm-visualisation-trip-segments-with-distance-metric.ipynb), now the relationships make much more sense. If you agree I will merge this with master and close this issue.

**Comment by rmitsch** [comment]
Minor nitpick: `_get_row_entries_for_trip(trip,  sensor_type="acceleration")` and `_cut_trip(sensor_data, snippet_length=30, column_names=None)` should be declared as `@staticmethod`.

I might have chosen not to merge the functionality of cutting snippets and calculating the distance matrix into one function with two different types of returned values, but that's a subjective design decision.

Agree to merge. See #18 for further comments on next steps.

**Comment by Lumik7** [comment]
Thanks for the feedback, I will refactor the code and push again. I didn't
think too much about the design.

**Comment by Lumik7** [comment]
Implemented suggestions, if you agree I will merge

**Comment by rmitsch** [comment]
Go ahead.

**Comment by Lumik7** [comment]
merged branches [here](https://github.com/univie-datamining-team3/assignment2/commit/7c14f993b29a824377881dbe362dde4de9381e7f). Close this issue
