### ISSUE TITLE
Preprocessing:  Normalize all recorded trips to same hertz rate

### ISSUE THREAD

**Issue by Lumik7** [univie-datamining-team3/assignment2#2]
Create a method in preprocessing.py that deals with the following issue:
From task description:
"The smartphones maybe do not record with the same frequency. Normalize all recorded                          
trips to a hertz rate of 20, that is 20 entries per second. Perform this via PAA (piecewise                                    
aggregate approximation) "

**Comment by MoBran** [comment]
done
