### ISSUE TITLE
Optimize/investigate t-SNE hyperparameter set

### ISSUE THREAD

**Issue by rmitsch** [univie-datamining-team3/assignment2#20]
Grid search/optimization to determine (1) intrinsic dimensionality of our dataset and (2) best set of hyperparameters for accurate low-dim. representation of target data.

**Comment by rmitsch** [comment]
Implemented. Will deduct optimization and summarize results here before closing.

**Comment by rmitsch** [comment]
Implemented. See [notebook](https://github.com/univie-datamining-team3/assignment2/blob/master/notebooks/5.0-lm-optimization-tsne.ipynb) for exemplary usage.

Despite employing Bayesian optimization, trying various quality measures and calculating a few hundred models, the results don't improve on existing models a lot (if at all). Maybe the objective (currently intra-cluster entropy and neighbourhood ) is still not ideal or I wasn't patient enough - anyway: I'd suggest to merge into master, close this issue and focus on other open issues. If there's enough time and motivation, we can still come back to this.

**Comment by Lumik7** [comment]
Agree

Am 29.12.2017 12:00 vorm. schrieb "Raphael Mitsch" <notifications@github.com
