### ISSUE TITLE
Distance measures: Implement dynamic time warping

### ISSUE THREAD

**Issue by rmitsch** [univie-datamining-team3/assignment2#21]
See implementation of n2-norm for template.

**Comment by rmitsch** [comment]
@Lumik7 @MoBran Implemented in 0a8d190. It takes a while though despite compiling against Cython and although I added multithreading - currently taking benchmarks. 

Suggesting a merge. If there are any obvious performance improvements, we can open up separate issues for them.

Note that this commit requires new dependencies - check `requirements.txt`.

**Comment by rmitsch** [comment]
Takes about 17 minutes on my laptop for all trips available so far. Think that's decent.

**Comment by Lumik7** [comment]
sounds good to me. Haven't done anything with multithreading or cython in python before, so I cannot really suggest any improvements right away, but 17 minutes should be fine

**Comment by rmitsch** [comment]
Ad Cython: Me neither, but the code of the module I'm using compiles against Cython (if it's active) at time of module installation. Happens automatically.
Ad multithreading: It's rather easy. If you want to check it out, see [`def _calculate_distance_with_dtw(data, norm: int = 1)`](https://github.com/univie-datamining-team3/assignment2/blob/011ca7e2cef10129df5c96236dca6ff6032e9e8e/src/data/preprocessing.py#L253) and [`DTWThread`](https://github.com/univie-datamining-team3/assignment2/blob/master/src/data/DTWThread.py).

Merged.
