### ISSUE TITLE
Implement evaluation procedure for clustering results

### ISSUE THREAD

**Issue by rmitsch** [univie-datamining-team3/assignment2#27]
What's our ground truth? Transport modes?

Depends partially (we can start with evaluating against transport mode clusters) on #31.
Is a dependency for #23 and #25.

Might just extend/generalize existing evaluation for k-means.

**Comment by Lumik7** [comment]
We could use a MDL approach, which works without a ground truth and just measures how good the clustering compresses the underlying data. It has a model assumption though.
