### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by rmitsch** [univie-datamining-team3/assignment2#30]
Requirements?

**Comment by Lumik7** [comment]
I would suggest to split the documentation in to the following sections:

1) Introduction
  Short Description of the assignment

2) Data Collection
  Which transport modes?
  How many trips?
  What devices were used?
  What issues did we face?

3) Preprocessing
  Which steps did we implement?
  What distance measures?

4) Visualisation and Exploratory Data Analysis
  Summary of collected trips
  Plot accelerometer sensor data of one selected trip.
  Plot GPS data

5) Clustering
  Description of the code used to get the following:
   - Clustering of one dimensional "n2" time series
   - Clustering of 3-dimensional (x,y,z) time series
   - Which distance metric and why?
   - Evaluation with clustering metric
  
Update:
I made a template on [overleaf](https://www.overleaf.com) and send the cooperation link in our chat.
