### ISSUE TITLE
Define (subclasses in) ground truth

### ISSUE THREAD

**Issue by rmitsch** [univie-datamining-team3/assignment2#31]
What's our ground truth? Against which clusters do we want to evaluate?
Transport modes is a no-brainer, but after that - 
- Person collecting the trip data?
- Tram/metro line?
- Time of the day (could make a difference when taking the tram, not with walking or metro though)?

Do we want want to evaluate against both scripted and unscripted trips?

**Comment by Lumik7** [comment]
Another mode most probably would be "idle", which means in this context standing still e.g. while waiting for a traffic light

**Comment by rmitsch** [comment]
Do you think that being idle/standing still would last long enough to fill up a 30s segment?

**Comment by Lumik7** [comment]
For the ordinary trips one could be waiting at a traffic light for one
segment

Am 07.01.2018 2:27 nachm. schrieb "Raphael Mitsch" <notifications@github.com

**Comment by rmitsch** [comment]
Alright. So our clusters could be combinations of:
- **Mode** (tram, metro, walk, idle)
- **Person**
- **Scripted/Unscripted**

That'd be up to 24 possible clusters. Automatic evaluation of clustering results might be a little tough, since we don't know how many/which clusters might actually be distinguished. Maybe interactive/visual exploration?

**Comment by Lumik7** [comment]
sounds good

> Maybe interactive/visual exploration?

what technique would you suggest?

**Comment by rmitsch** [comment]
I'd probably start with using [scatterplots with plotly](https://plot.ly/python/line-and-scatter/).
