### ISSUE TITLE
Preprocessing: Calculate 2-norm for accelerometer data

### ISSUE THREAD

**Issue by Lumik7** [univie-datamining-team3/assignment2#4]
Create a method in preprocessing.py that deals with the following issue:
From task description:
"The 3-dimensional accelerometer sensor does not provide direct information about how                      
the human moves, but only in an indirect way. It provides direct information about how                              
the smartphone device moves (that’s why we differ between the scripted and ordinary                          
trips). To be able to compare two trips with different orientations of the smartphone, one                              
way is to simply calculate the 2-norm of the 3-dimensional signal (which equals the                            
column “total”) for each point of time. Calculate the 2-norm of the preprocessed 3-dim                            
accelerometer time series. "

**Comment by rmitsch** [comment]
Changes: Added `Preprocessor._recalculate_accerelometer_2norm(resampled_sensor_values)` recalculating column `total` in resampled trip data.
Merged to master.
