### ISSUE TITLE
Pipeline: Implement a pipeline script for all steps

### ISSUE THREAD

**Issue by Lumik7** [univie-datamining-team3/assignment2#8]
Create a batch file or python script, etc. to glue all tasks together, in order to conveniently execute all steps.

**Comment by rmitsch** [comment]
@Lumik7 @MoBran I'd suggest using a Python script, since a batch file is OS-dependent and we use different systems. Agreed?

**Comment by Lumik7** [comment]
agreed!

**Comment by Lumik7** [comment]
Can this be closed?

**Comment by rmitsch** [comment]
We don't have a dedicated pipeline script yet, I believe (do we?). I would suggest not closing this issue.

**Comment by Lumik7** [comment]
No, we don't have one. Alright
